### ISSUE TITLE
Packages that use common js fail at run time

### ISSUE THREAD

**Issue by grothem** [scaffold-eth/scaffold-eth-typescript#41] opened 2021-12-11 02:52 UTC
**Describe the bug**
I added the `ipfs-http-client` package, and when running `yarn start` there's an error trying to load electron. If you look at that stack trace, the package has a dependency that tries to load electron via require.

**To Reproduce**
1. Checkout this branch: https://github.com/scaffold-eth/scaffold-eth-typescript-challenges/tree/challenge-0-simple-nft
2. Run `yarn & yarn start`

**Expected behavior**
Packages that use common js shouldn't cause a runtime failure

**Additional context**
I tried configuring @originjs/vite-plugin-commonjs, but I still had the same error

**Comment by ShravanSunder** [comment] 2021-12-20 04:30
@grothem i pushed a fix in the typescript challenges branch

https://github.com/scaffold-eth/scaffold-eth-typescript-challenges/commit/78a4c78c573b42ba5250364a77a560739d50ab13

**Comment by grothem** [comment] 2021-12-21 03:51
Thanks @ShravanSunder 

I pulled your changes. Now I'm getting a runtime error from a dependency of `ipfs-http-client`, the `multiaddr` package. The full error is:
```
SyntaxError: The requested module '/node_modules/multiaddr/src/index.js?v=8c972f98' does not provide an export named 'Multiaddr'
```

I tried a few different things with the `vite.config.ts` file, but I wasn't able to fix the error. I pushed to that branch, so if you pull latest and try to run it, you should see the same error.

**Comment by grothem** [comment] 2021-12-21 19:19
Made some progress on this, I added the dependency to the `include` array in the config. I kept adding them as the errors popped up, but now the `ipfs-utils` package is throwing that error. Adding that to the `include` array does not work.

**Comment by ShravanSunder** [comment] 2021-12-30 16:18
@grothem  i think i found a solution.  see https://github.com/scaffold-eth/scaffold-eth-typescript-challenges/commit/7d761c45eb658fcbe4c06f126bc231f15dde258e

This was also caused by issues I with the ipfs library and their dependencies.  Basically the package requires electron for some reason after v47 and this is a unresolved issue.

**Closed** 2021-12-30 16:25 UTC
